package h

// Attr* constants provide compile-time safety for HTML attribute names.
// Using these constants prevents typos and enables LSP autocompletion.
const (
	AttrAccept              = "accept"
	AttrAcceptCharset       = "accept-charset"
	AttrAccessKey           = "accesskey"
	AttrAction              = "action"
	AttrAlign               = "align"
	AttrAllow               = "allow"
	AttrAlpha               = "alpha"
	AttrAlt                 = "alt"
	AttrAs                  = "as"
	AttrAsync               = "async"
	AttrAutocapitalize      = "autocapitalize"
	AttrAutocomplete        = "autocomplete"
	AttrAutofocus           = "autofocus"
	AttrAutoplay            = "autoplay"
	AttrBackground          = "background"
	AttrBgColor             = "bgcolor"
	AttrBorder              = "border"
	AttrCapture             = "capture"
	AttrCharset             = "charset"
	AttrChecked             = "checked"
	AttrCite                = "cite"
	AttrClass               = "class"
	AttrColor               = "color"
	AttrColorSpace          = "colorspace"
	AttrCols                = "cols"
	AttrColSpan             = "colspan"
	AttrContent             = "content"
	AttrContentEditable     = "contenteditable"
	AttrControls            = "controls"
	AttrCoords              = "coords"
	AttrCrossOrigin         = "crossorigin"
	AttrCsp                 = "csp"
	AttrData                = "data"
	AttrDateTime            = "datetime"
	AttrDecoding            = "decoding"
	AttrDefault             = "default"
	AttrDefer               = "defer"
	AttrDir                 = "dir"
	AttrDirName             = "dirname"
	AttrDisabled            = "disabled"
	AttrDownload            = "download"
	AttrDraggable           = "draggable"
	AttrEnctype             = "enctype"
	AttrEnterKeyHint        = "enterkeyhint"
	AttrElementTiming       = "elementtiming"
	AttrForm                = "form"
	AttrFormAction          = "formaction"
	AttrFormEnctype         = "formenctype"
	AttrFormMethod          = "formmethod"
	AttrFormNoValidate      = "formnovalidate"
	AttrFormTarget          = "formtarget"
	AttrFetchPriority       = "fetchpriority"
	AttrHeaders             = "headers"
	AttrHeight              = "height"
	AttrHidden              = "hidden"
	AttrHigh                = "high"
	AttrHref                = "href"
	AttrHrefLang            = "hreflang"
	AttrHttpEquiv           = "http-equiv"
	AttrID                  = "id"
	AttrIntegrity           = "integrity"
	AttrInputMode           = "inputmode"
	AttrIsMap               = "ismap"
	AttrItemProp            = "itemprop"
	AttrKind                = "kind"
	AttrLabel               = "label"
	AttrLang                = "lang"
	AttrLanguage            = "language"
	AttrLoading             = "loading"
	AttrList                = "list"
	AttrLoop                = "loop"
	AttrLow                 = "low"
	AttrMax                 = "max"
	AttrMaxLength           = "maxlength"
	AttrMinLength           = "minlength"
	AttrMedia               = "media"
	AttrMethod              = "method"
	AttrMin                 = "min"
	AttrMultiple            = "multiple"
	AttrMuted               = "muted"
	AttrName                = "name"
	AttrNoValidate          = "novalidate"
	AttrOnAbort             = "onAbort"
	AttrOnActivate          = "onActivate"
	AttrOnAfterPrint        = "onAfterPrint"
	AttrOnAfterUpdate       = "onAfterUpdate"
	AttrOnBeforeActivate    = "onBeforeActivate"
	AttrOnBeforeCopy        = "onBeforeCopy"
	AttrOnBeforeCut         = "onBeforeCut"
	AttrOnBeforeDeactivate  = "onBeforeDeactivate"
	AttrOnBeforeEditFocus   = "onBeforeEditFocus"
	AttrOnBeforePaste       = "onBeforePaste"
	AttrOnBeforePrint       = "onBeforePrint"
	AttrOnBeforeUnload      = "onBeforeUnload"
	AttrOnBeforeUpdate      = "onBeforeUpdate"
	AttrOnBegin             = "onBegin"
	AttrOnBlur              = "onBlur"
	AttrOnBounce            = "onBounce"
	AttrOnCellChange        = "onCellChange"
	AttrOnChange            = "onChange"
	AttrOnClick             = "onClick"
	AttrOnContextMenu       = "onContextMenu"
	AttrOnControlSelect     = "onControlSelect"
	AttrOnCopy              = "onCopy"
	AttrOnCut               = "onCut"
	AttrOnDataAvailable     = "onDataAvailable"
	AttrOnDataSetChanged    = "onDataSetChanged"
	AttrOnDataSetComplete   = "onDataSetComplete"
	AttrOnDblClick          = "onDblClick"
	AttrOnDeactivate        = "onDeactivate"
	AttrOnDrag              = "onDrag"
	AttrOnDragEnd           = "onDragEnd"
	AttrOnDragLeave         = "onDragLeave"
	AttrOnDragEnter         = "onDragEnter"
	AttrOnDragOver          = "onDragOver"
	AttrOnDragDrop          = "onDragDrop"
	AttrOnDragStart         = "onDragStart"
	AttrOnDrop              = "onDrop"
	AttrOnEnd               = "onEnd"
	AttrOnError             = "onError"
	AttrOnErrorUpdate       = "onErrorUpdate"
	AttrOnFilterChange      = "onFilterChange"
	AttrOnFinish            = "onFinish"
	AttrOnFocus             = "onFocus"
	AttrOnFocusIn           = "onFocusIn"
	AttrOnFocusOut          = "onFocusOut"
	AttrOnHashChange        = "onHashChange"
	AttrOnHelp              = "onHelp"
	AttrOnInput             = "onInput"
	AttrOnKeyDown           = "onKeyDown"
	AttrOnKeyPress          = "onKeyPress"
	AttrOnKeyUp             = "onKeyUp"
	AttrOnLayoutComplete    = "onLayoutComplete"
	AttrOnLoad              = "onLoad"
	AttrOnLoseCapture       = "onLoseCapture"
	AttrOnMediaComplete     = "onMediaComplete"
	AttrOnMediaError        = "onMediaError"
	AttrOnMessage           = "onMessage"
	AttrOnMouseDown         = "onMouseDown"
	AttrOnMouseEnter        = "onMouseEnter"
	AttrOnMouseLeave        = "onMouseLeave"
	AttrOnMouseMove         = "onMouseMove"
	AttrOnMouseOut          = "onMouseOut"
	AttrOnMouseOver         = "onMouseOver"
	AttrOnMouseUp           = "onMouseUp"
	AttrOnMouseWheel        = "onMouseWheel"
	AttrOnMove              = "onMove"
	AttrOnMoveEnd           = "onMoveEnd"
	AttrOnMoveStart         = "onMoveStart"
	AttrOnOffline           = "onOffline"
	AttrOnOnline            = "onOnline"
	AttrOnOutOfSync         = "onOutOfSync"
	AttrOnPaste             = "onPaste"
	AttrOnPause             = "onPause"
	AttrOnPopState          = "onPopState"
	AttrOnProgress          = "onProgress"
	AttrOnPropertyChange    = "onPropertyChange"
	AttrOnReadyStateChange  = "onReadyStateChange"
	AttrOnRedo              = "onRedo"
	AttrOnRepeat            = "onRepeat"
	AttrOnReset             = "onReset"
	AttrOnResize            = "onResize"
	AttrOnResizeEnd         = "onResizeEnd"
	AttrOnResizeStart       = "onResizeStart"
	AttrOnResume            = "onResume"
	AttrOnReverse           = "onReverse"
	AttrOnRowsEnter         = "onRowsEnter"
	AttrOnRowExit           = "onRowExit"
	AttrOnRowDelete         = "onRowDelete"
	AttrOnRowInserted       = "onRowInserted"
	AttrOnScroll            = "onScroll"
	AttrOnSeek              = "onSeek"
	AttrOnSelect            = "onSelect"
	AttrOnSelectionChange   = "onSelectionChange"
	AttrOnSelectStart       = "onSelectStart"
	AttrOnStart             = "onStart"
	AttrOnStop              = "onStop"
	AttrOnStorage           = "onStorage"
	AttrOnSyncRestored      = "onSyncRestored"
	AttrOnSubmit            = "onSubmit"
	AttrOnTimeError         = "onTimeError"
	AttrOnTrackChange       = "onTrackChange"
	AttrOnUndo              = "onUndo"
	AttrOnUnload            = "onUnload"
	AttrOnURLFlip           = "onURLFlip"
	AttrOpen                = "open"
	AttrOptimum             = "optimum"
	AttrPattern             = "pattern"
	AttrPing                = "ping"
	AttrPlaceholder         = "placeholder"
	AttrPlaysInline         = "playsinline"
	AttrPoster              = "poster"
	AttrPopoverTargetAction = "popovertargetaction"
	AttrPreload             = "preload"
	AttrReadonly            = "readonly"
	AttrReferrerPolicy      = "referrerpolicy"
	AttrRel                 = "rel"
	AttrRequired            = "required"
	AttrReversed            = "reversed"
	AttrRole                = "role"
	AttrRows                = "rows"
	AttrRowSpan             = "rowspan"
	AttrSandbox             = "sandbox"
	AttrScope               = "scope"
	AttrSelected            = "selected"
	AttrShape               = "shape"
	AttrSize                = "size"
	AttrSizes               = "sizes"
	AttrSlot                = "slot"
	AttrSpan                = "span"
	AttrSpellCheck          = "spellcheck"
	AttrSrc                 = "src"
	AttrSrcDoc              = "srcdoc"
	AttrSrcLang             = "srclang"
	AttrSrcSet              = "srcset"
	AttrStart               = "start"
	AttrStep                = "step"
	AttrStyle               = "style"
	AttrSummary             = "summary"
	AttrTabIndex            = "tabindex"
	AttrTarget              = "target"
	AttrTitle               = "title"
	AttrTranslate           = "translate"
	AttrType                = "type"
	AttrUseMap              = "usemap"
	AttrValue               = "value"
	AttrWidth               = "width"
	AttrWrap                = "wrap"
)

// Type* constants are valid values for the type attribute on various elements.
const (
	TypeText          = "text"
	TypePassword      = "password"
	TypeCheckbox      = "checkbox"
	TypeRadio         = "radio"
	TypeSubmit        = "submit"
	TypeReset         = "reset"
	TypeButton        = "button"
	TypeFile          = "file"
	TypeHidden        = "hidden"
	TypeImage         = "image"
	TypeColor         = "color"
	TypeDate          = "date"
	TypeDateTime      = "datetime"
	TypeDateTimeLocal = "datetime-local"
	TypeEmail         = "email"
	TypeMonth         = "month"
	TypeNumber        = "number"
	TypeRange         = "range"
	TypeSearch        = "search"
	TypeTel           = "tel"
	TypeTime          = "time"
	TypeUrl           = "url"
	TypeWeek          = "week"
)

// Rel* constants are valid values for the rel attribute.
const (
	RelAlternate             = "alternate"
	RelAuthor                = "author"
	RelBookmark              = "bookmark"
	RelCanonical             = "canonical"
	RelCompressionDictionary = "compression-dictionary"
	RelDnsPrefetch           = "dns-prefetch"
	RelExternal              = "external"
	RelHelp                  = "help"
	RelIcon                  = "icon"
	RelLicense               = "license"
	RelManifest              = "manifest"
	RelModulePreload         = "modulepreload"
	RelNext                  = "next"
	RelNoFollow              = "nofollow"
	RelNoOpener              = "noopener"
	RelNoReferrer            = "noreferrer"
	RelOpener                = "opener"
	RelPingback              = "pingback"
	RelPreconnect            = "preconnect"
	RelPrefetch              = "prefetch"
	RelPreload               = "preload"
	RelPrerender             = "prerender"
	RelPrev                  = "prev"
	RelSearch                = "search"
	RelStylesheet            = "stylesheet"
	RelTag                   = "tag"
)

// Target* constants are valid values for the target attribute.
const (
	TargetBlank     = "_blank"
	TargetSelf      = "_self"
	TargetParent    = "_parent"
	TargetTop       = "_top"
	TargetFramename = "framename"
)

// Method* constants are valid values for the method attribute on <form>.
const (
	MethodGet  = "get"
	MethodPost = "post"
)

// Enctype* constants are valid values for the enctype attribute on <form>.
const (
	EnctypeUrlEncoded    = "application/x-www-form-urlencoded"
	EnctypeMultipartForm = "multipart/form-data"
	EnctypePlainText     = "text/plain"
)

// CrossOrigin* constants are valid values for the crossorigin attribute.
const (
	CrossOriginAnonymous      = "anonymous"
	CrossOriginUseCredentials = "use-credentials"
)

// Dir* constants are valid values for the dir attribute.
const (
	DirLtr  = "ltr"
	DirRtl  = "rtl"
	DirAuto = "auto"
)

// Translate* constants are valid values for the translate attribute.
const (
	TranslateYes = "yes"
	TranslateNo  = "no"
)

// Preload* constants are valid values for the preload attribute on <audio> and <video>.
const (
	PreloadNone     = "none"
	PreloadMetadata = "metadata"
	PreloadAuto     = "auto"
)

// Loading* constants are valid values for the loading attribute on <img> and <iframe>.
const (
	LoadingLazy  = "lazy"
	LoadingEager = "eager"
)

// Decoding* constants are valid values for the decoding attribute on <img>.
const (
	DecodingAsync = "async"
	DecodingSync  = "sync"
	DecodingAuto  = "auto"
)

// ReferrerPolicy* constants are valid values for the referrerpolicy attribute.
const (
	ReferrerPolicyNoReferrer                  = "no-referrer"
	ReferrerPolicyNoReferrerWhenDowngrade     = "no-referrer-when-downgrade"
	ReferrerPolicyOrigin                      = "origin"
	ReferrerPolicyOriginWhenCrossOrigin       = "origin-when-cross-origin"
	ReferrerPolicySameOrigin                  = "same-origin"
	ReferrerPolicyStrictOriginWhenCrossOrigin = "strict-origin-when-cross-origin"
	ReferrerPolicyUnsafeUrl                   = "unsafe-url"
)

// FetchPriority* constants are valid values for the fetchpriority attribute.
const (
	FetchPriorityLow  = "low"
	FetchPriorityHigh = "high"
	FetchPriorityAuto = "auto"
)

// EnterKeyHint* constants are valid values for the enterkeyhint attribute.
const (
	EnterKeyHintEnter    = "enter"
	EnterKeyHintDone     = "done"
	EnterKeyHintGo       = "go"
	EnterKeyHintNext     = "next"
	EnterKeyHintPrevious = "previous"
	EnterKeyHintSearch   = "search"
	EnterKeyHintSend     = "send"
)

// Wrap* constants are valid values for the wrap attribute on <textarea>.
const (
	WrapHard = "hard"
	WrapSoft = "soft"
	WrapOff  = "off"
)

// Shape* constants are valid values for the shape attribute on <area>.
const (
	ShapeDefault = "default"
	ShapeCircle  = "circle"
	ShapePoly    = "poly"
	ShapeRect    = "rect"
)

// Spellcheck* constants are valid values for the spellcheck attribute.
const (
	SpellCheckTrue  = "true"
	SpellCheckFalse = "false"
)

// ContentEditable* constants are valid values for the contenteditable attribute.
const (
	ContentEditableTrue          = "true"
	ContentEditableFalse         = "false"
	ContentEditablePlaintextOnly = "plaintext-only"
)

// Draggable* constants are valid values for the draggable attribute.
const (
	DraggableTrue  = "true"
	DraggableFalse = "false"
)

// InputMode* constants are valid values for the inputmode attribute.
const (
	InputModeNone    = "none"
	InputModeText    = "text"
	InputModeDecimal = "decimal"
	InputModeNumeric = "numeric"
	InputModeTel     = "tel"
	InputModeSearch  = "search"
	InputModeEmail   = "email"
	InputModeUrl     = "url"
)

// PopoverTargetAction* constants are valid values for the popovertargetaction attribute.
const (
	PopoverTargetActionHide   = "hide"
	PopoverTargetActionShow   = "show"
	PopoverTargetActionToggle = "toggle"
)

// Autocomplete* constants are valid values for the autocomplete attribute.
const (
	AutocompleteOff                 = "off"
	AutocompleteOn                  = "on"
	AutocompleteName                = "name"
	AutocompleteHonorificPrefix     = "honorific-prefix"
	AutocompleteGivenName           = "given-name"
	AutocompleteAdditionalName      = "additional-name"
	AutocompleteFamilyName          = "family-name"
	AutocompleteHonorificSuffix     = "honorific-suffix"
	AutocompleteNickname            = "nickname"
	AutocompleteEmail               = "email"
	AutocompleteUsername            = "username"
	AutocompleteNewPassword         = "new-password"
	AutocompleteCurrentPassword     = "current-password"
	AutocompleteOneTimeCode         = "one-time-code"
	AutocompleteOrganizationTitle   = "organization-title"
	AutocompleteOrganization        = "organization"
	AutocompleteStreetAddress       = "street-address"
	AutocompleteAddressLine1        = "address-line1"
	AutocompleteAddressLine2        = "address-line2"
	AutocompleteAddressLine3        = "address-line3"
	AutocompleteAddressLevel4       = "address-level4"
	AutocompleteAddressLevel3       = "address-level3"
	AutocompleteAddressLevel2       = "address-level2"
	AutocompleteAddressLevel1       = "address-level1"
	AutocompleteCountry             = "country"
	AutocompleteCountryName         = "country-name"
	AutocompleteCcName              = "cc-name"
	AutocompleteCcGivenName         = "cc-given-name"
	AutocompleteCcAdditionalName    = "cc-additional-name"
	AutocompleteCcFamilyName        = "cc-family-name"
	AutocompleteCcNumber            = "cc-number"
	AutocompleteCcExp               = "cc-exp"
	AutocompleteCcExpMonth          = "cc-exp-month"
	AutocompleteCcExpYear           = "cc-exp-year"
	AutocompleteCcCsc               = "cc-csc"
	AutocompleteCcType              = "cc-type"
	AutocompleteTransactionCurrency = "transaction-currency"
	AutocompleteTransactionAmount   = "transaction-amount"
	AutocompleteLanguage            = "language"
	AutocompleteBday                = "bday"
	AutocompleteBdayDay             = "bday-day"
	AutocompleteBdayMonth           = "bday-month"
	AutocompleteBdayYear            = "bday-year"
	AutocompleteSex                 = "sex"
	AutocompleteTelCountryCode      = "tel-country-code"
	AutocompleteTelNational         = "tel-national"
	AutocompleteTelAreaCode         = "tel-area-code"
	AutocompleteTelLocal            = "tel-local"
	AutocompleteTelExtension        = "tel-extension"
	AutocompleteImpp                = "impp"
	AutocompleteUrl                 = "url"
	AutocompletePhoto               = "photo"
)

// Sandbox* constants are valid values for the sandbox attribute on <iframe>.
const (
	SandboxAllowForms                         = "allow-forms"
	SandboxAllowModals                        = "allow-modals"
	SandboxAllowOrientationLock               = "allow-orientation-lock"
	SandboxAllowPointerLock                   = "allow-pointer-lock"
	SandboxAllowPopups                        = "allow-popups"
	SandboxAllowPopupsToEscapeSandbox         = "allow-popups-to-escape-sandbox"
	SandboxAllowPresentation                  = "allow-presentation"
	SandboxAllowSameOrigin                    = "allow-same-origin"
	SandboxAllowScripts                       = "allow-scripts"
	SandboxAllowTopNavigation                 = "allow-top-navigation"
	SandboxAllowTopNavigationByUserActivation = "allow-top-navigation-by-user-activation"
)
