package hx

// Event* constants are htmx event names.
// Use these constants with AttrOn for type-safe inline event handlers.
const (
	EventAbort                 = "htmx:abort"
	EventAfterOnLoad           = "htmx:after-on-load"
	EventAfterProcessNode      = "htmx:after-process-node"
	EventAfterRequest          = "htmx:after-request"
	EventAfterSettle           = "htmx:after-settle"
	EventAfterSwap             = "htmx:after-swap"
	EventBeforeCleanupElement  = "htmx:before-cleanup-element"
	EventBeforeOnLoad          = "htmx:before-on-load"
	EventBeforeProcessNode     = "htmx:before-process-node"
	EventBeforeRequest         = "htmx:before-request"
	EventBeforeSend            = "htmx:before-send"
	EventBeforeSettle          = "htmx:before-settle"
	EventBeforeSwap            = "htmx:before-swap"
	EventConfigRequest         = "htmx:config-request"
	EventConfirm               = "htmx:confirm"
	EventHistoryCacheError     = "htmx:history-cache-error"
	EventHistoryCacheMiss      = "htmx:history-cache-miss"
	EventHistoryCacheMissError = "htmx:history-cache-miss-error"
	EventHistoryRestore        = "htmx:history-restore"
	EventLoad                  = "htmx:load"
	EventNoSseSourceError      = "htmx:no-sse-source-error"
	EventOnLoadError           = "htmx:on-load-error"
	EventOobAfterSwap          = "htmx:oob-after-swap"
	EventOobBeforeSwap         = "htmx:oob-before-swap"
	EventOobErrorNoTarget      = "htmx:oob-error-no-target"
	EventPrompt                = "htmx:prompt"
	EventResponseError         = "htmx:response-error"
	EventSendError             = "htmx:send-error"
	EventSseError              = "htmx:sse-error"
	EventSseOpen               = "htmx:sse-open"
	EventSseMessage            = "htmx:sse-message"
	EventSwapError             = "htmx:swap-error"
	EventTargetError           = "htmx:target-error"
	EventTimeout               = "htmx:timeout"
	EventValidationValidate    = "htmx:validation:validate"
	EventValidationFailed      = "htmx:validation:failed"
	EventValidationHalted      = "htmx:validation:halted"
	EventXhrAbort              = "htmx:xhr:abort"
	EventXhrLoadend            = "htmx:xhr:loadend"
	EventXhrLoadstart          = "htmx:xhr:loadstart"
	EventXhrProgress           = "htmx:xhr:progress"
)
